Fix ImportError when supersmoother is installed as a dependency
When other packages install supersmoother as one of their dependecncies
it's not safe to import supersmoother during the install phase. This is
because supersmoother's own dependencies might not be installed yet, e.g.
numpy.

This change will fix the following error:

    $ pip install .[full]
    Processing /home/alex/src/pandashells
    Collecting numpy (from pandashells==0.1.4)
      Downloading numpy-1.9.2.tar.gz (4.0MB)
    ...
    Collecting supersmoother (from pandashells==0.1.4)
      Downloading supersmoother-0.3.1.tar.gz (572kB)
        100% |████████████████████████████████| 573kB 991kB/s
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 20, in <module>
          File "/tmp/pip-build-kYP8xD/supersmoother/setup.py", line 22, in <module>
            import supersmoother
          File "supersmoother/__init__.py", line 6, in <module>
            from .smoother import MovingAverageSmoother, LinearSmoother
          File "supersmoother/smoother.py", line 2, in <module>
            import numpy as np
        ImportError: No module named numpy

        ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-kYP8xD/supersmoother